import { BaseAgent } from "./BaseAgent.js";

export class ArchitectAgent extends BaseAgent {
  constructor(projectId) { super(projectId, "ArchitectAgent"); }
  
  async execute(context) {
    this.status = "running";
    this.emit("AGENT_STARTED", { context });
    try {
      const research = this.readArtifact("RESEARCH.md") || "No research";
      const req = this.readArtifact("REQ.md") || "No requirements";
      
      const architecture = `# Architecture\n\nBased on:\n- REQ size: ${req.length}\n- RESEARCH size: ${research.length}\n\n(Generated by ArchitectAgent)`;
      this.writeArtifact("ARCHITECTURE.md", architecture, { state: "DRAFT" });
      
      this.status = "completed";
      this.emit("AGENT_COMPLETED", { artifact: "ARCHITECTURE.md" });
      return { ok: true };
    } catch (e) {
      this.status = "failed";
      this.emit("AGENT_FAILED", { error: e.message });
      return { ok: false, error: e.message };
    }
  }
}
